services:
  nginx-proxy:
    image: nginx:stable-alpine
    container_name: nginx-proxy
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./ssl:/etc/nginx/ssl:ro
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "5"
